### ISSUE TITLE
Sparkpost TLS option `true` breaks smtp-connection

### ISSUE THREAD

**Issue by localnerve** [nodemailer/nodemailer-wellknown#18]
The setting for the Sparkpost `tls` option is true.

However, [smtp-connection](https://github.com/nodemailer/smtp-connection/blob/fc0135ba722e27718af798760c1ace8801e10642/lib/smtp-connection.js#L550) expects an object, which crashes.

I'm not sure if the setting is wrong, the code in `smtp-connection`, both, or if Sparkpost is not supported w/SMTP transport anymore.

Please let me know how I can help.

**Comment by localnerve** [comment]
Just did a test with the sparkpost `tls` option set to false.

Wireshark showed SMTP EHLO, STARTTLS, and then TLSv1.2 communication for the remainder of the transmission.

**Comment by andris9** [comment]
Yes, you're right. I removed the tls option as it was not needed anyway https://github.com/nodemailer/nodemailer-wellknown/commit/c3ad18054f876d7a9301548e82d0cfef61309cfd#diff-f5fb0346ca2de022483b15e81d888f18L202

**Comment by localnerve** [comment]
nodemailer, nodemailer-smtp-transport, etc are all pinned by version, so
this 0.1.8 update cannot be realized.

Is it possible to change the dependency versions for these modules so the
updates can get through?
I would just PR, but I'm not sure how you would like to do this, update
semver spec, nodemailer-smtp-transport only, re-pin everything, etc.).



On Mon, Apr 4, 2016 at 5:56 AM, Andris Reinman <notifications@github.com>
wrote:

> Closed #18 <https://github.com/nodemailer/nodemailer-wellknown/issues/18>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nodemailer/nodemailer-wellknown/issues/18#event-613348254>
>



-- 
Alex Grant
President
LocalNerve, LLC
http://www.localnerve.com
207-370-8005
