### ISSUE TITLE
Amazon SNS doesn't work with other regions

### ISSUE THREAD

**Issue by flyte** [nodemailer/nodemailer-wellknown#5]
Amazon SNS is region sensitive, so if like me you have SNS set up with `eu-west-1`, the `host` string of `email-smtp.us-east-1.amazonaws.com` will not work. It will instead return:

    554 Message rejected: Email address is not verified.

because you (probably) haven't verified any email addresses to send from in the `us-east-1` region.

I'm trying to set up the 'ghost' blogging platform, but even when I specify the `host` address in config.js, it gets overridden with `email-smtp.us-east-1.amazonaws.com`. So I suppose the real issue is that you can't override 'wellknown' settings.

**Comment by noderat** [comment]
Created PR #19 to address this.

**Comment by noderat** [comment]
@andris9 You can mark this issue as resolved since you merged my PR #21
